Create Backend Documentation
AmadoSuarez/AssetTracker pull request #7
Opened 2018-11-19 17:35 UTC by salam4

PMs Please review .

Thanks,
Saqeb

2018-12-12 16:23 UTC, AmadoSuarez requested changes

2018-12-12 16:23 UTC, AmadoSuarez commented on Backend Documentation
> +## AssetTracker Built with Node.JS
We are using Ruby on Rails for the backend.

2018-12-12 16:23 UTC, AmadoSuarez commented on Backend Documentation
> +*Why use Node.JS for AssetTracket?*
Ruby on Rails

2018-12-14 16:21 UTC, salam4 commented on Backend Documentation
> +## AssetTracker Built with Node.JS
I fixed the documentation.

2018-12-14 16:21 UTC, salam4 commented on Backend Documentation
> +*Why use Node.JS for AssetTracket?*
I fixed the documentation

2018-12-14 16:22 UTC, AmadoSuarez approved these changes

2018-12-14 16:23 UTC, AmadoSuarez commented
LGTM! 🚢 Merge it!

2018-12-14 16:30 UTC, merged